#!/bin/bash
# Build + deploy the lovhistorie PUBLIC site.
#
# Usage:
#   bash build.sh site      # build static site in build/site/ (plaintext)
#   bash build.sh deploy    # build + push to hsigstad/lovhistorie gh-pages (PUBLIC)
#   bash build.sh render    # re-render index.html from existing laws/ data (fast, no re-extract)
#
# The site is PUBLIC (plaintext) — SITE_GATED=0. It has two layers:
#   1. the interactive statute browser (index.html + laws/*.json), generated by
#      source.site.browser from the pipeline;
#   2. the reference docs (goal/evaluation/status/examples/...) under docs/,
#      generated by sitekit (source.site.build_all).
# The browser is the landing page; it links to the docs. Building the browser data
# re-reconstructs every dev law, so a full `deploy` is slow (minutes); use `render`
# to iterate on the page template without re-extracting.
#
# Deploy requirements: git push access to hsigstad/lovhistorie.

set -euo pipefail
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Public site: deploy build/site/ plaintext (no staticrypt gate).
export SITE_GATED=0
SITE_TITLE="Lovhistorie"
source "$PROJECT_DIR/../../research-kit/tools/site_deploy.sh"
MODE="${1:-site}"

has_data() { [ -d data/current ] || [ -n "${LOVHISTORIE_CURRENT_DIR:-}" ]; }

build_site() {
    cd "$PROJECT_DIR"
    if has_data; then
        echo "=== Refreshing performance snapshot (source.eval.status) ==="
        python3 -m source.eval.status || echo "  (status refresh skipped — keeping committed snapshot)"
        echo "=== Refreshing worked examples (source.eval.examples) ==="
        python3 -m source.eval.examples || echo "  (examples refresh skipped — keeping committed page)"
    fi
    echo "=== Building reference docs (sitekit) ==="
    python3 -m source.site.build_all
    if has_data; then
        echo "=== Building statute browser (source.site.browser) ==="
        # Runs AFTER sitekit so the browser landing overwrites sitekit's index.html.
        python3 -m source.site.browser || echo "  (browser build skipped — keeping sitekit landing)"
    else
        echo "  (no data — keeping sitekit reading-guide as landing)"
    fi
}

case "$MODE" in
    site)   build_site ;;
    deploy) build_site; sk_deploy_site ;;
    render) cd "$PROJECT_DIR"; LOVHISTORIE_BROWSER_RENDER_ONLY=1 python3 -m source.site.browser ;;
    push)   sk_deploy_site ;;   # deploy the already-built build/site/ without rebuilding
    *) echo "Usage: bash build.sh [site|deploy|render|push]"; exit 1 ;;
esac
